import React from 'react'
import './SystemColor.css'
export default function SystemColor () {
	return (
		<div className='SystemColor_SystemColor'>
			<span className='SystemColorsLight'>System Colors Light</span>
			<span className='BaseColor'>Base Color</span>
			<span className='SystemBackground'>System Background</span>
			<span className='SeparatorsColor'>Separators Color</span>
			<span className='FillsColor'>Fills Color</span>
			<span className='TextColor'>Text Color</span>
			<span className='TextLinkColor'>Text Link Color</span>
			<span className='PrimaryColor'>Primary Color</span>
			<div className='ColorPallet'/>
			<div className='ColorPallet_1'/>
			<div className='ColorPallet_2'/>
			<div className='ColorPallet_3'/>
			<div className='ColorPallet_4'/>
			<div className='ColorPallet_5'/>
			<span className='Black'>Black</span>
			<span className='Primary'>Primary</span>
			<span className='ButtonFill'>Button Fill</span>
			<span className='Title'>Title</span>
			<span className='_85'>85%</span>
			<div className='ColorPallet_6'/>
			<div className='ColorPallet_7'/>
			<div className='ColorPallet_8'/>
			<div className='ColorPallet_9'/>
			<span className='_30'>30%</span>
			<span className='_10'>10%</span>
			<span className='Purple'>Purple</span>
			<span className='White'>White</span>
			<span className='White_1'>White</span>
			<span className='Secondary'>Secondary</span>
			<span className='Primary_1'>Primary</span>
			<span className='Secondary_1'>Secondary</span>
			<span className='ImagePlaceholder'>Image Placeholder</span>
			<span className='ProgressContainer'>Progress Container</span>
			<span className='TextField'>Text Field</span>
			<span className='Icon'>Icon</span>
			<span className='Disabled'>Disabled</span>
			<span className='Body1'>Body 1</span>
			<span className='_70'>70%</span>
			<div className='ColorPallet_10'/>
			<div className='ColorPallet_11'/>
			<div className='ColorPallet_12'/>
			<div className='ColorPallet_13'/>
			<div className='ColorPallet_14'/>
			<div className='ColorPallet_15'/>
			<span className='TextField2'>Text Field 2</span>
			<div className='ColorPallet_16'/>
			<div className='ColorPallet_17'/>
			<div className='ColorPallet_18'/>
			<div className='ColorPallet_19'/>
			<div className='ColorPallet_20'/>
			<span className='Body2'>Body 2</span>
			<span className='_50'>50%</span>
			<div className='ColorPallet_21'/>
			<span className='Body2_1'>Body 2</span>
			<div className='ColorPallet_22'/>
			<div className='ColorPallet_23'/>
			<span className='SecondaryColor'>Secondary Color</span>
			<div className='ColorPallet_24'/>
			<span className='_85_1'>85%</span>
			<div className='ColorPallet_25'/>
			<div className='ColorPallet_26'/>
			<span className='_30_1'>30%</span>
			<span className='_10_1'>10%</span>
			<span className='_70_1'>70%</span>
			<div className='ColorPallet_27'/>
			<span className='_50_1'>50%</span>
			<div className='ColorPallet_28'/>
			<span className='Accent1Color'>Accent 1 Color</span>
			<div className='ColorPallet_29'/>
			<span className='_85_2'>85%</span>
			<div className='ColorPallet_30'/>
			<div className='ColorPallet_31'/>
			<span className='_30_2'>30%</span>
			<span className='_10_2'>10%</span>
			<span className='_70_2'>70%</span>
			<div className='ColorPallet_32'/>
			<span className='_50_2'>50%</span>
			<div className='ColorPallet_33'/>
			<span className='OtherColor'>Other Color</span>
			<div className='ColorPallet_34'/>
			<span className='Warning'>Warning</span>
			<div className='ColorPallet_35'/>
			<span className='Info'>Info</span>
			<span className='ERROR'>ERROR</span>
			<div className='ColorPallet_36'/>
			<span className='Success'>Success</span>
			<div className='ColorPallet_37'/>
		</div>
	)
}